---
title: "Remodeling oncolytic virotherapy"
author: "Orfeas Gkourlias & Dennis Wiersma"
date: '2022-06-17'

output: 
  pdf_document: 
    highlight: kate
    number_sections: yes
    citation_package: natbib
    
    includes: 
      in_header: latex/preamble.tex
      before_body: latex/prefix.tex
      
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("code/main.R")
```

\newpage
\section{Introduction}

Viruses and cancer are both considered to be very destructive and harmful. But what if one of these could be used to combat the other? Viruses infect cells. These cells do not have to be healthy ones. By introduction of specific viruses into tumor affected tissue, the tumor may be repressed and eventually entirely eliminated. The field known as oncolytic virotherapy is still developing. There's still many uncertainties, but also possibilities. This paper aims to reproduce and possibly revise another paper published in the journal of theoretical biology. The paper demonstrated extensive modelling relevant to exploring the effects of varying amounts of normal and tumor cells.

Oncolytic virotherapy has a lot of potential. With that comes many things to consider. Before diving deeper and challenging some of these considerations in more mathematical detail, let's ask some general important questions. What is the desired balance of infection? Viruses used in these treatments don't exclusively infect tumor cells. This could either be beneficial or a hindrance. At which amount of infection does one group start to suffer? And what are the ideal ratios when it comes to tumor to normal cell infection? As the amount of tumor cells declines, it becomes harder for the virus in the system to find and infect tumor cells before the immune system eliminates the virus completely. This could result in stray tumor cells being left behind, only delaying the growth until it propagates significantly again. This is also only addressing the use of viruses which lyses the tumor cells. Some viral infections may cause the cells to be more susceptible to other forms of treatment, such as chemotherapy. This brings in a whole other amount of variables to consider.

In any case, the immune response is of great importance. The immune response may vary from person to person and tissue to tissue. Whether the person had been exposed to a virus before, or the immune system engages an unknown pathogen mediates different responses too. It's important to be aware of those factors in treatment. Time is of the essence in all instances of virotherapy. It usually takes 5 to 7 days for the immune response to completely halt production rate of the virus. As mentioned earlier, it's important that the treatment, in the case of the lysation approach, destroys all of the tumor cells. Having to accomplish this in the time frame of only 5 to 7 days is quite a feat. This swift approach is referred to as one shot virotherapy. This is why it's so important for the initial values to be right, further solidifying the significance of researching and being absolutely certain about the relevant mathematical models, due to there only being one shot at the initial treatment with a specific virus.

\newpage

\section{Methods}

Since the ambition of this paper is to reproduce the results found in @OKAMOTO2014166, our objectives are the same as described in that article:  
"We model the dynamics of an oncolytic virus within the context of its interactions with the populations of tumor cells and normal cells. We integrate key ecological processes, such as the growth of normal cells and tumor cells and an adaptive immune response, with an explicit treatment of how viruses differentially exploit the two cell types."

\subsection{Variables}

\begin{table}[h]
\begin{tabular}{ |l||l|l|  }
  \hline
  \textbf{Variable} & \textbf{Explanation} & \textbf{Unit} \\
  \hline
  \hline
  $t$ & Time & hr\textsuperscript{-1} \\
  \hline
  $H$ & Normal (Healthy) cell type & - \\
  \hline
  $C$ & Tumour (Cancerous) cell type & - \\
  \hline
  $H_S$ & Normal cell that is susceptible & - \\
  \hline
  $H_I$ & Normal cell that is infected & - \\
  \hline
  $C_S$ & Tumour cell that is susceptible & - \\
  \hline
  $C_I$ & Tumour cell that is infected & - \\
  \hline
  $K_H$ & Carrying capacity of normal cells & cells \\
  \hline
  $K_C$ & Carrying capacity of tumour cells & cells \\
  \hline
  $\beta_H$ & Infection rate of normal cells & viruses cell\textsuperscript{-1} hr\textsuperscript{-1}\\
  \hline
  $\beta_C$ & Infection rate of tumour cells & viruses cell\textsuperscript{-1} hr\textsuperscript{-1} \\
  \hline
  $\lambda_H$ & Lysing rate of normal cells & cell\textsuperscript{-1} hr\textsuperscript{-1} \\
  \hline
  $\lambda_C$ & Lysing rate of tumour cells & cell\textsuperscript{-1} hr\textsuperscript{-1}\\
  \hline
  $b_{H}$ & Burst size of normal cells & - \\
  \hline
  $b_C$ & Burst size of tumour cells & - \\
  \hline
  $r_H$ & Per-capita growth rate of normal cells & hr\textsuperscript{-1}\\
  \hline
  $r_C$ & Per-capita growth rate of tumour cells & hr\textsuperscript{-1}\\
  \hline
  $\omega$ & Rate of neutralisation by innate immune response & virus\textsuperscript{-1} hr\textsuperscript{-1}\\
  \hline
  $v$ & Virions & - \\
  \hline
\end{tabular}
\caption{All variables and their respective explanations}
\label{table:vars}
\end{table}


\subsection{Equations}
This model is a direct replica of the one presented in @OKAMOTO2014166, since that is the process we are trying to replicate. The model seeks to incorporate the effects of an oncolytic virus on the growth and maintenance of normal cells along with it's effects on tumour cells, thereby extending the work of @Wu:2004wn which only aims to formulate the latter: characterising an oncolytic virus infecting a population of tumour cells. @Wu:2004wn is itself an extension of previous models of virus-host interactions, further references to which van be found in @OKAMOTO2014166.

We start out with two separate cell populations both of which are divided into two sub populations: tumour cells ($C$) and normal cells ($H$), each having a susceptible ($C_S$ & $H_S$) and an infected ($C_I$ & $H_I$) sub population. All other parameter definitions can be found in table \ref{table:vars}

\subsubsection{Normal susceptible cell count}
This first differential equation models the change in the number of normal cells that are still susceptible to an infection by virus particles. 

\begin{equation} \label{eq:dHs} 
  \frac{dH_{S}}{dt} = r_H H_S (1 - \frac{(H_S + H_I)}{K_H}) - H_S \beta_H v
\end{equation}

\subsubsection{Tumour susceptible cell count}
This second differential equation is very similar to equation \eqref{eq:dHs}, since it represents the same change in susceptible cells except it models tumour cells instead of normal ones.

\begin{equation} \label{eq:dCs} 
  \frac{dC_S}{dt} = r_C C_S (1 - \frac{(C_S + C_I)}{K_C}) - C_S \beta_C v
\end{equation}

\subsubsection{Normal infected cell count}
This third differential equation is again similar to equation \eqref{eq:dHs} in that it models normal cells, but in this case we're looking at the change in infected cells instead of susceptible ones.

\begin{equation} \label{eq:dHI} 
  \frac{dH_I}{dt} = \beta_H H_S v - \lambda_H H_I
\end{equation}

\subsubsection{Tumour infected cell count}
This fourth differential equation relates to equation \eqref{eq:dHI} in the same way as equation \eqref{eq:dCs} relates to equation \eqref{eq:dHs}: This equation again models infected cells, but regards tumour cells instead of the normal cells found in equation \eqref{eq:dHI}

\begin{equation} \label{eq:dCI} 
  \frac{dC_I}{dt} = \beta_C C_S v - \lambda_C C_I
\end{equation}

\subsubsection{Virion count}
This fifth and final differential equation is a bit different from all of the other ones that came before, since it models virions instead of cell populations. 

\begin{equation} \label{eq:dv} 
  \frac{dv}{dt} = b_C \lambda_C C_I + b_H b_C \lambda_H H_I - \beta_H H_S v - \beta_C C_S - \omega v
\end{equation}

\newpage

\subsection{Equation modeling}
The results of the differential equations and their plots are made by an R program, 
utilizing the desolve and ggplot packages.
By defining the parameters, variables and equations, analysis of results
was made convenient. Changing and observing the effect of certain parameter 
values were easily done this way. The equations remained unchanged, stored as functions.

The goal in this process was to simulate the effects the three viruses 
in particular would have on tumour affected tissue. 
To further determine the most important elements of the equations, 
different values were changed according to what would logically be most 
influential, to confirm their importance. The specific values will be mentioned 
when discussing the equations themselves.


Starting out with the equation execution required
distinction between parameters and state variables. 
The state variables are universal, and not specific to any virus.
They are rather bodily constants, which were exposed to the effects of the different viruses.
The amount of virus particles introduced to a system is a state variable, and 
initially remains the same for all viruses when t = 0. it is however worth noting
that the amount of free virus particles are ever changing, and don't 
just reach 0 after they have infected cells. The virus replication rate differs.
It is because of the complex interactions such as these that the virus types are important.
There are 4 additional variables to the state variable mentioned above. These
account for the susceptible and infected cells, both healthy and cancerous.

By letting desolve run the equations over 168 hours, three different datasets 
were created. One for every type of virus. By 10log transforming the data,
comparing the differing effects was now possible. By plotting the three datsets,
using ggplot, there seemed to be significant difference between the virus effects.
To deduce what contributed to the different effects, the virus specific 
variables were compared next to the plotted results.

After simply observing the plot lines and making a rough estimation, 
it seemed that the main contributing differentiators are related to cell death
and cell infcetion specificity.
Lysing and burst rates being the main culpritswhen it comes to cell death
The infection rate of healthy cells, betaH, 
being very relevant to specicifity. To further analyse this, the
values were changed from the original values, which can be found in the sections above.

To reaffirm the previous suspicion, new plots were made with both lowered and 
increased values. Analysis of these findings are under the results section.
\newpage

\section{Results}
By finishing the simulations and plotting the results, multiple things are clear.
With the default values, there seems to be a clear indication that competition
is important. It's important that theres relative balance between infection rates of 
healthy and tumour cells. The healthy cells can be slightly slower when it come to
being infected, but not significantly.

As can be seen in the plot above, when a virus only affects the cancerous cells,
the results differ significantly. Further establishing that the competition 
is of great importance to the results. The balancing of healthy and cancerous
cells being absent affects Ci and Cs. The Ci increases at first, as usual. But
without healthy cells being infected too, it seems that Ci and V drop off swiftly.
This means that Cs increases accordingly, which means cancerous cells grow faster
than they are being eliminated. With V0 hitting 0, the treatment comes to a premature
stop. The immune system most likely being its stongest then. 

In addition to observing the specificity, the virus destructivity was also adjsuted
and plotted. Gradual increases seem to also rapidly decrease the Ci and Hi.
These two seem to decrease significantly slower when using the default values.
As the gradual increases kept stacking up, it became clear that the Cs and Hs
also hit the 0 point earlier. This makes sense, because cells get lysed
increasingly faster. It is also worth noting that V0 seems to decrease very slowly.
Something that is different when observing the default values. This woud also
explain why infections seem to happen quicker, because of the burst size being
increased. Resulting in more virus particles in the system, at a faster rate.


\newpage

\section{Discussion}
The conclusions and dicoveries made in this paper will surely be helpful
for future studies. But there could be some points of discussion on a number of topics.
The first ones relating to the accuracy of the variables involved. While this paper
aimed to simulate the possbilties to the best of it's abilities, the process remains
very complex, with a lot of parts involved. The point being that maybe not all 
influental parts have yet been taken into consideration. References were briefly
made to the immune response and its relevance to ending the treatment in 7 days.
The immunology aspect of this paper did not go into thorough detail in
descrbing the underlying mechanisms which facilitate virus elimination. It is therefore
entirely possible that something coudl've been missed in this consideration. But
the immunology aspects this paper is based on come from reliable sources, such as
Oxford university press. Nevertheless, it is probably useful to dive into the
immunological relevance further in another paper.

While on the topic of the complexity, there's more to be remarked on this subject.
Not all forms of cancer will respond in the same way to the viruses discussed.
This paper lays a foundation, from which more specific forms of cancer may
be modeled too. The same goes for the viruses mentioned. There are plethera of
viruses out there, which would surely offer a world of opportunity when it comes
to modeling of new responses.

The critiques mentioned above are worthy of being explored further. This doesn't
trivialize the fact that the models created here are important. The results are
very promising in finding new ways to treat cancer. The basis of the models
are sound and could surely be used for future research. As mentioned before,
the specificity of future papers may lead to actual trials of the treatments.

\newpage

\section{Conclusion}
There's several conclusions which can be made on the basis of the models.
As stated in the prior paper this one is based on, the compettivity is once again
reinforced as an important elemenet in virotherapy. The absence of such a mechanism
surely inhibits the ability for the virus to help in treatment. Many factors go into
ensuring this competition between cells, viruses and immune system. Most of the 
important variables being controllable, like the specificity of the virus.what

\newpage

\section{Bibliography}
