---
title: "3.Detailed_analysis"
author: "Dennis Wiersma"
date: '2022-05-16'
output: 
  pdf_document:
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(deSolve)
```

# Comparing simulation data with experimental data for two dosis

```{r}
data <- read.csv("MPL.csv", na.strings = "NA")

median_MPL_01 <- median(data$MPL_conc[data$dose==0.1], na.rm=T)
median_MPL_03 <- median(data$MPL_conc[data$dose==0.3], na.rm=T)

D01 = median_MPL_01 * 1000 / 374.471
D03 = median_MPL_03 * 1000 / 374.471

```

# Assignment 1

```{r}
parameters <- c(
  k.s_Rm = 2.90,
  IC.50_Rm = 26.2,
  k.on = 0.00329,
  k.T = 0.63,
  k.re = 0.57,
  Rf = 0.49,
  k.d_R = 0.0572,
  k.d_Rm = 0.612,
  k.s_r = 3.22,
  D = 0
)

state <- c(
  R.m0 = 4.74,
  R.0 = 267,
  DR = 0,
  DRN = 0
)

# glucocorticoid receptor dynamics
GRD <- function(t, state, parameters){
  with(as.list(c(state, parameters)),{
    
    dR.m <- k.s_Rm * (1 - DRN / (IC.50_Rm + DRN) - k.d_Rm * R.m0)
    
    dR <- k.s_r * R.m0 + Rf * k.re * DRN - k.on * D * R.0 - k.d_R * R.0
    
    dDR <- k.on * D * R.0 - k.T * DR
    
    dDRN <- k.T * DR - k.re * DRN
    
    return(list(c(dR.m, dR, dDR, dDRN)))
  }
  )
}

# Duration of 7 days, defined in hours
times <- seq(0, 168)

# Median values of experimental data per time value
medians <- aggregate(data[,c("MPL_conc","mRNA","Free_receptor")],
                     list(data$dose,data$time), median, na.rm=T)
names(medians)[1:2] <- c("dose","time")

# Sets parameter D to value for 0.1 mg drug/kg rat/h value
parameters["D"] = D01
# Performs the modelling function
out01 <- ode(y = state, times = times, func = GRD, parms = parameters)

# Sets parameter D to value for 0.3 mg drug/kg rat/h value
parameters["D"] = D03
# Performs the modelling function
out03 <- ode(y = state, times = times, func = GRD, parms = parameters)

par(mfrow = c(2,2))
# Plots a scatter plot with experimental data for Rm where dose == 0.1 mg drug/kg rat/h
plot(data$mRNA ~ data$time, 
     main = "Rm (0.1 mg drug/kg rat/h)", 
     ylab = "Rm (fmol/g liver)", 
     xlab = "Time")
# Adds the model for Rm as a black line
lines(out01[,2])
# Adds medians of the experimental data for Rm as a red line
lines(medians[medians["dose"] == 0.1,]$mRNA ~ medians[medians["dose"] == 0.1,]$time, 
      col = "red")

# Plots a scatter plot with experimental data for R where dose == 0.1 mg drug/kg rat/h
plot(data$Free_receptor ~ data$time, 
     main = "R (0.1 mg drug/kg rat/h)", 
     ylab = "R (fmol/mg protein)", 
     xlab = "Time")
# Adds the model for R as a black line
lines(out01[,3])
# Adds medians of the experimental data for R as a red line
lines(medians[medians["dose"] == 0.1,]$Free_receptor ~ medians[medians["dose"] == 0.1,]$time, 
      col = "red")

# Plots a scatter plot with experimental data for Rm where dose == 0.3 mg drug/kg rat/h
plot(data$mRNA ~ data$time, 
     main = "Rm (0.3 mg drug/kg rat/h)", 
     ylab = "Rm (fmol/g liver)", 
     xlab = "Time")
# Adds the model for Rm as a black line
lines(out03[,2])
# Adds medians of the experimental data for Rm as a red line
lines(medians[medians["dose"] == 0.3,]$mRNA ~ medians[medians["dose"] == 0.3,]$time, 
      col = "red")

# Plots a scatter plot with experimental for R data where dose == 0.3 mg drug/kg rat/h
plot(data$Free_receptor ~ data$time, 
     main = "R (0.3 mg drug/kg rat/h)", 
     ylab = "R (fmol/mg protein)", 
     xlab = "Time")
# Adds the model for R as a black line
lines(out03[,3])
# Adds medians of the experimental data for R as a red line
lines(medians[medians["dose"] == 0.3,]$Free_receptor ~ medians[medians["dose"] == 0.3,]$time, 
      col = "red")

```

